import './styles.css';
import { contextPercent } from '../interaction/context.js';
import type { ActivityEvent, ContextUsage, RequestExecution } from '../interaction/types.js';
import { isHostMessage, type ChatOptions, type ClientMessage, type ComposerAttachment, type TaskDashboard } from '../shared/messages.js';

declare const acquireVsCodeApi: () => { postMessage(message: ClientMessage): void };
const vscode = acquireVsCodeApi(); const app = document.querySelector<HTMLDivElement>('#app')!;
let generating = false; let currentAssistant: HTMLElement | undefined; let attachments: ComposerAttachment[] = []; let options: ChatOptions | undefined;
let execution: RequestExecution | undefined; let activity: ActivityEvent[] = []; let context: ContextUsage = { unit: 'tokens', estimated: false, reason: 'Context usage is not available yet.' }; let timer: number | undefined; let dashboard: TaskDashboard | undefined;
let modelReasoning = new Map<string, boolean>();

app.innerHTML = `<div class="tool-shell">
  <header class="topbar"><span class="mark" aria-label="LGS">L</span><span class="connection"><i id="status-dot"></i><span id="state">Connecting…</span></span><span class="spacer"></span><button class="icon" id="new" title="New conversation" aria-label="New conversation">＋</button><button class="icon" id="settings" title="Settings" aria-label="Settings">⚙</button></header>
  <details class="history-menu"><summary>History <span id="session-count"></span></summary><div id="chats"></div></details>
  <div id="provider-notice" hidden></div><div id="error-region" aria-live="assertive"></div>
  <main id="history" aria-live="polite"><div class="empty">Ask LGS to do something…</div></main>
  <section id="request-status" hidden></section>
  <section id="completion" hidden><button id="completion-toggle"><span><i></i>Verification</span><span id="completion-progress"></span></button><div id="completion-checklist" hidden></div></section>
  <section class="composer" aria-label="Command surface"><form id="composer-form">
    <div id="attachment-chips" class="attachment-chips"></div>
    <textarea id="prompt" rows="2" placeholder="Ask LGS to do something..." aria-label="Request"></textarea>
    <div class="composer-toolbar">
      <details class="context-add"><summary class="tool-button" aria-label="Add context" title="Add context">＋</summary><div class="menu"><button id="attach" type="button"><b>File or image</b><span>Attach repository context</span></button></div></details>
      <input id="attachment-input" type="file" multiple hidden>
      <details class="context-popover"><summary id="context-meter" class="context-meter" aria-label="Context usage"><span></span></summary><div id="context-detail" class="popover"></div></details>
      <span class="separator"></span>
      <select id="profile" class="compact-select" aria-label="Provider profile"></select>
      <select id="model" class="compact-select model-select" aria-label="Model"><option value="">Discovering…</option></select>
      <select id="thinking" class="compact-select" aria-label="Reasoning level" hidden><option value="auto">Auto</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select>
      <span class="separator mode-separator"></span>
      <select id="mode" class="compact-select mode-select" aria-label="Execution mode"><option value="normal">Normal</option><option value="plan">Plan</option><option value="web">Web</option><option value="research">Research</option></select>
      <details class="more"><summary class="tool-button" title="Execution policy">•••</summary><div class="popover policy"><label>Approval<select id="approval"><option value="on-request">On request</option><option value="always">Always ask</option><option value="never">Never allow</option></select></label><label><input id="cap-terminal" type="checkbox" data-capability="terminal"> Terminal</label><label><input id="cap-browser" type="checkbox" data-capability="browser"> Browser</label><label><input id="cap-computer" type="checkbox" data-capability="computer"> Computer</label><button id="usage-link" type="button">Open usage</button></div></details>
      <span class="spacer"></span><button id="stop" class="stop" type="button" hidden>Stop</button><button id="send" class="send" type="submit" aria-label="Send">↑</button>
    </div>
  </form></section>
</div>`;

const history = query<HTMLElement>('#history'), input = query<HTMLTextAreaElement>('#prompt'), send = query<HTMLButtonElement>('#send'), stop = query<HTMLButtonElement>('#stop');
const profile = query<HTMLSelectElement>('#profile'), model = query<HTMLSelectElement>('#model'), thinking = query<HTMLSelectElement>('#thinking'), mode = query<HTMLSelectElement>('#mode'), approval = query<HTMLSelectElement>('#approval');

query('#settings').addEventListener('click', () => vscode.postMessage({ type: 'openSettings' })); query('#new').addEventListener('click', () => vscode.postMessage({ type: 'newChat' }));
query('#usage-link').addEventListener('click', () => vscode.postMessage({ type: 'openUsage' })); profile.onchange = () => vscode.postMessage({ type: 'selectProfile', profileId: profile.value }); model.onchange = () => { thinking.hidden = modelReasoning.get(model.value) !== true; vscode.postMessage({ type: 'selectModel', model: model.value }); };
mode.onchange = syncOptions; thinking.onchange = syncOptions; approval.onchange = syncOptions; app.querySelectorAll<HTMLInputElement>('[data-capability]').forEach(control => control.onchange = syncOptions);
query('#composer-form').addEventListener('submit', event => { event.preventDefault(); const text = input.value.trim(); if (!text || generating) return; clearError(); addMessage('user', text, false, attachments); input.value = ''; resize(); vscode.postMessage({ type: 'userMessage', text, attachments }); attachments = []; renderAttachments(); });
input.addEventListener('keydown', event => { if (event.key === 'Enter' && (event.metaKey || event.ctrlKey)) { event.preventDefault(); query<HTMLFormElement>('#composer-form').requestSubmit(); } }); input.addEventListener('input', resize);
stop.onclick = () => vscode.postMessage({ type: 'cancel' }); const fileInput = query<HTMLInputElement>('#attachment-input'); query('#attach').addEventListener('click', () => fileInput.click()); fileInput.onchange = () => { void addFiles(fileInput.files, 'composer'); fileInput.value = ''; };
query('.composer').addEventListener('dragover', event => event.preventDefault()); query('.composer').addEventListener('drop', event => { event.preventDefault(); void addFiles((event as DragEvent).dataTransfer?.files, 'drop'); }); input.addEventListener('paste', event => { if (event.clipboardData?.files.length) { event.preventDefault(); void addFiles(event.clipboardData.files, 'clipboard'); } });
query('#completion-toggle').addEventListener('click', () => { const list = query<HTMLElement>('#completion-checklist'); list.hidden = !list.hidden; });

window.addEventListener('message', ({ data }: MessageEvent<unknown>) => {
  if (!isHostMessage(data)) return;
  switch (data.type) {
    case 'appearance': document.documentElement.dataset.lgsTheme = data.theme; break;
    case 'profiles': profile.replaceChildren(...data.profiles.map(item => option(item.id, item.name))); profile.value = data.selected; break;
    case 'models': modelReasoning = new Map(data.models.map(item => [item.id, item.reasoning === true])); model.replaceChildren(...(data.models.length ? data.models.map(item => option(item.id, item.displayName || item.id)) : [option('', 'No models')])); model.value = data.selected; thinking.hidden = modelReasoning.get(data.selected) !== true; break;
    case 'options': options = data.options; mode.value = options.mode; thinking.value = options.thinking; approval.value = options.approval; Object.entries(options.capabilities).forEach(([key, enabled]) => { const control = app.querySelector<HTMLInputElement>(`[data-capability="${key}"]`); if (control) control.checked = enabled; }); break;
    case 'chatList': renderChats(data.chats); break;
    case 'chatLoaded': history.innerHTML = ''; execution = undefined; activity = []; query<HTMLElement>('#request-status').hidden = true; if (data.messages.length) data.messages.forEach(item => addMessage(item.role, item.text, false, item.attachments)); else renderEmpty(); break;
    case 'state': query('#state').textContent = data.state; query('#status-dot').className = /error|no enabled/i.test(data.state) ? 'error' : /connecting/i.test(data.state) ? 'busy' : 'ready'; break;
    case 'streamStart': generating = true; clearError(); send.hidden = true; stop.hidden = false; input.disabled = true; currentAssistant = addMessage('assistant', '', true); break;
    case 'textDelta': if (currentAssistant) { currentAssistant.textContent += data.text; history.scrollTop = history.scrollHeight; } break;
    case 'streamEnd': generating = false; send.hidden = false; stop.hidden = true; input.disabled = false; currentAssistant = undefined; break;
    case 'error': showError(data.message); generating = false; send.hidden = false; stop.hidden = true; input.disabled = false; break;
    case 'requestExecution': execution = data.request; activity = data.events; renderExecution(); break;
    case 'contextUsage': context = data.usage; renderContext(); break;
    case 'providerNotice': renderProvider(data); break;
    case 'completionState': renderCompletion(data.state); break;
    case 'taskDashboard': dashboard = data.dashboard; break;
  }
});

function syncOptions(): void { if (!options) return; const capabilities = { ...options.capabilities }; app.querySelectorAll<HTMLInputElement>('[data-capability]').forEach(control => { capabilities[control.dataset.capability as keyof typeof capabilities] = control.checked; }); options = { ...options, mode: mode.value as ChatOptions['mode'], thinking: thinking.value as ChatOptions['thinking'], approval: approval.value as ChatOptions['approval'], capabilities, autoResearch: mode.value === 'research' ? 'proactive' : options.autoResearch }; vscode.postMessage({ type: 'setOptions', options }); }
function renderExecution(): void {
  if (!execution) return; const root = query<HTMLElement>('#request-status'); root.hidden = false; const active = execution.status === 'active';
  root.innerHTML = `<div class="working-row"><span><i class="${active ? 'busy' : execution.status}"></i>${active ? 'Working' : title(execution.status)} · <time id="elapsed">${elapsed(execution)}</time></span><button id="details-toggle">Details</button></div><div id="phase-details" hidden>${execution.phases.map(phase => `<div class="phase ${phase.status}"><i>${phaseMark(phase.status)}</i><div><b>${escapeHtml(phase.name)}</b><span>${escapeHtml(phase.goal)}</span>${phase.result ? `<small>${escapeHtml(phase.result)}</small>` : ''}</div><time>${phaseDuration(phase)}</time></div>`).join('')}<div class="trace-actions"><span>${activity.length} events</span><button id="open-activity">Open activity log</button>${dashboard ? '<button id="open-evidence">Open task evidence</button>' : ''}</div></div>`;
  query('#details-toggle').addEventListener('click', () => { const details = query<HTMLElement>('#phase-details'); details.hidden = !details.hidden; query('#details-toggle').textContent = details.hidden ? 'Details' : 'Hide'; }); query('#open-activity').addEventListener('click', () => vscode.postMessage({ type: 'openActivity' })); query('#open-evidence')?.addEventListener('click', () => vscode.postMessage({ type: 'taskAction', action: 'viewTaskState' }));
  if (timer) window.clearInterval(timer); if (active) timer = window.setInterval(() => { const target = app.querySelector('#elapsed'); if (target && execution) target.textContent = elapsed(execution); }, 1000);
}
function renderContext(): void { const percent = contextPercent(context), meter = query<HTMLElement>('#context-meter'); meter.style.setProperty('--context', `${(percent || 0) * 3.6}deg`); meter.classList.toggle('unknown', percent === undefined); meter.title = context.used !== undefined && context.maximum !== undefined ? `${format(context.used)} / ${format(context.maximum)} tokens · ${percent}% used` : context.reason || 'Context usage unavailable'; const categories = context.categories ? Object.entries(context.categories).map(([name, value]) => `<div><span>${title(name)}</span><b>${format(value)} tokens</b></div>`).join('') : ''; query('#context-detail').innerHTML = `<b>Context</b><span>${context.used === undefined ? 'Usage unavailable' : `${format(context.used)} / ${format(context.maximum!)} tokens`}</span>${percent === undefined ? `<small>${escapeHtml(context.reason || '')}</small>` : `<small>${percent}% used${context.estimated ? ' · estimated' : ''}</small>`}${categories ? `<div class="context-categories">${categories}</div>` : ''}`; }
function renderProvider(data: Extract<import('../shared/messages.js').HostMessage, { type: 'providerNotice' }>): void { const root = query<HTMLElement>('#provider-notice'); if (data.state === 'running') { root.hidden = true; root.innerHTML = ''; return; } root.hidden = false; const reconnect = !data.canStart && !data.canRestart && data.state !== 'starting'; root.innerHTML = `<div><b>${escapeHtml(data.provider)} ${data.state}</b><span>${escapeHtml(data.message || '')}</span></div><div>${data.canStart ? '<button data-provider="start">Start</button>' : ''}${data.canRestart ? '<button data-provider="restart">Restart</button>' : reconnect ? '<button data-provider="refresh">Reconnect</button>' : ''}<button data-provider="settings">Settings</button><button data-provider="logs">Details</button></div>`; root.querySelectorAll<HTMLButtonElement>('[data-provider]').forEach(button => button.onclick = () => vscode.postMessage({ type: 'providerAction', action: button.dataset.provider as 'start' | 'restart' | 'refresh' | 'settings' | 'logs' })); }
function renderCompletion(value: Extract<import('../shared/messages.js').HostMessage, { type: 'completionState' }>['state']): void { const root = query<HTMLElement>('#completion'); root.hidden = false; root.dataset.status = value.status; query('#completion-progress').textContent = `${value.progress.passed}/${value.progress.required}`; query('#completion-checklist').innerHTML = value.checklist.filter(item => item.required).map(item => `<div class="check ${item.passed ? 'passed' : ''}"><i>${item.passed ? '✓' : '○'}</i><span><b>${escapeHtml(item.label)}</b><small>${escapeHtml(item.detail)}</small></span></div>`).join(''); }
function addMessage(kind: string, text: string, loading = false, contextItems?: AttachmentSummary[]): HTMLElement { history.querySelector('.empty')?.remove(); const row = document.createElement('article'); row.className = `message-row ${kind}`; const label = document.createElement('span'); label.className = 'message-label'; label.textContent = kind === 'user' ? 'You' : 'LGS'; const body = document.createElement('div'); body.className = 'message'; body.textContent = text; if (loading) body.classList.add('streaming'); row.append(label); if (contextItems?.length) { const list = document.createElement('div'); list.className = 'message-context'; for (const item of contextItems) { const chip = document.createElement('span'); chip.textContent = item.name; chip.title = `${item.mediaType} · ${formatBytes(item.bytes)}`; list.append(chip); } row.append(list); } row.append(body); history.append(row); history.scrollTop = history.scrollHeight; return body; }
type AttachmentSummary = { name: string; mediaType: string; bytes: number };
async function addFiles(files: FileList | null | undefined, source: ComposerAttachment['source']): Promise<void> { if (!files) return; for (const file of Array.from(files).slice(0, 20 - attachments.length)) { if (!file.size || file.size > 25 * 1024 * 1024) { showError(`${file.name} must be between 1 byte and 25 MB.`); continue; } attachments.push({ id: crypto.randomUUID(), name: file.name, mediaType: file.type || 'application/octet-stream', bytes: file.size, dataBase64: await fileBase64(file), source }); } renderAttachments(); }
function renderAttachments(): void { const root = query<HTMLElement>('#attachment-chips'); root.replaceChildren(...attachments.map(item => { const chip = document.createElement('span'); chip.className = 'attachment-chip'; chip.textContent = item.name; chip.title = `${item.mediaType} · ${formatBytes(item.bytes)}`; const remove = document.createElement('button'); remove.type = 'button'; remove.textContent = '×'; remove.onclick = () => { attachments = attachments.filter(value => value.id !== item.id); renderAttachments(); }; chip.append(remove); return chip; })); }
function fileBase64(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.readAsDataURL(file); }); }
function renderChats(items: { id: string; title: string; updatedAt: number }[]): void { query('#session-count').textContent = items.length ? String(items.length) : ''; query('#chats').innerHTML = items.map(item => `<button data-chat="${escapeHtml(item.id)}"><span>${escapeHtml(item.title)}</span><time>${relative(item.updatedAt)}</time></button>`).join('') || '<span class="quiet">No conversations</span>'; app.querySelectorAll<HTMLButtonElement>('[data-chat]').forEach(button => button.onclick = () => vscode.postMessage({ type: 'loadChat', chatId: button.dataset.chat! })); }
function showError(message: string): void { query('#error-region').innerHTML = `<div class="error"><div><b>LGS stopped</b><span>${escapeHtml(message)}</span></div><button>Dismiss</button></div>`; query('#error-region button').addEventListener('click', clearError); }
function clearError(): void { query('#error-region').innerHTML = ''; } function renderEmpty(): void { history.innerHTML = '<div class="empty">Ask LGS to do something…</div>'; }
function resize(): void { input.style.height = 'auto'; input.style.height = `${Math.min(160, Math.max(52, input.scrollHeight))}px`; } function query<T extends HTMLElement = HTMLElement>(selector: string): T { return app.querySelector<T>(selector)!; }
function option(value: string, label: string): HTMLOptionElement { const item = document.createElement('option'); item.value = value; item.textContent = label; return item; } function escapeHtml(value: unknown): string { return String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!); }
function title(value: string): string { return value.charAt(0).toUpperCase() + value.slice(1).replace(/-/g, ' '); } function format(value: number): string { return new Intl.NumberFormat().format(value); } function formatBytes(value: number): string { return value < 1024 ? `${value} B` : value < 1024 * 1024 ? `${Math.round(value / 1024)} KB` : `${Math.round(value / 1024 / 1024 * 10) / 10} MB`; }
function relative(timestamp: number): string { const minutes = Math.max(0, Math.round((Date.now() - timestamp) / 60000)); return minutes < 1 ? 'now' : minutes < 60 ? `${minutes}m` : minutes < 1440 ? `${Math.round(minutes / 60)}h` : `${Math.round(minutes / 1440)}d`; }
function elapsed(request: RequestExecution): string { const end = request.endedAt ? Date.parse(request.endedAt) : Date.now(); return duration(Math.max(0, end - Date.parse(request.startedAt))); } function phaseDuration(phase: RequestExecution['phases'][number]): string { return phase.startedAt ? duration(Math.max(0, Date.parse(phase.endedAt || new Date().toISOString()) - Date.parse(phase.startedAt))) : ''; } function duration(ms: number): string { const seconds = Math.floor(ms / 1000), minutes = Math.floor(seconds / 60), hours = Math.floor(minutes / 60); return hours ? `${hours}h ${minutes % 60}m` : minutes ? `${minutes}m ${seconds % 60}s` : `${seconds}s`; } function phaseMark(status: string): string { return status === 'completed' ? '✓' : status === 'active' ? '●' : status === 'failed' || status === 'blocked' ? '!' : status === 'skipped' ? '–' : '○'; }

vscode.postMessage({ type: 'ready' });
