import * as vscode from 'vscode';
import type { UsageDashboard } from './types.js';
import type { UsageTracker } from './service.js';

export class UsageDashboardPanel {
  private panel?: vscode.WebviewPanel;
  constructor(private readonly tracker: UsageTracker) {}
  show(): void { this.panel ??= vscode.window.createWebviewPanel('lgs.usage', 'LGS Usage', vscode.ViewColumn.One, { enableScripts: false }); this.panel.webview.html = html(this.tracker.dashboard()); this.panel.reveal(); }
}

function html(dashboard: UsageDashboard): string {
  const currency = (value: number) => value ? `$${value.toFixed(4)}` : 'Unknown';
  const context = dashboard.records.filter(record => record.contextMaximum !== undefined && record.contextUtilized !== undefined).slice(-8).reverse().map(record => { const percent = Math.round(record.contextUtilized! / record.contextMaximum! * 100); const parts = Object.entries(record.contextBreakdown ?? {}).map(([key, value]) => `${key}: ${value}`).join(' · '); return `<div class="card"><strong>${escape(record.model ?? 'Unknown model')}</strong><br>${(record.contextUtilized! / 1000).toFixed(1)}K / ${(record.contextMaximum! / 1000).toFixed(0)}K<br>${percent}%${parts ? `<br><span class="muted">${escape(parts)}</span>` : ''}</div>`; }).join('');
  const billing = [...new Map(dashboard.records.filter(record => record.providerConnection).map(record => [record.providerConnection!, record.billing])).entries()].map(([connection, kind]) => `<div class="card"><strong>${escape(connection)}</strong><br>${kind === 'local' ? 'API monetary cost: local/not applicable' : kind === 'institution_provided' ? 'Institution-provided; no direct user charge known' : kind === 'commercial' ? 'Commercial API pricing' : 'Billing unknown'}</div>`).join('');
  const row = (label: string, values: { key: string; inputTokens: number; outputTokens: number; estimatedCostUsd: number; providerReportedCostUsd: number }[]) => `<h2>${escape(label)}</h2><table><tr><th>Name</th><th>Tokens</th><th>Provider cost</th><th>Estimated cost</th></tr>${values.slice(0, 12).map(value => `<tr><td>${escape(value.key)}</td><td>${value.inputTokens + value.outputTokens}</td><td>${currency(value.providerReportedCostUsd)}</td><td>${currency(value.estimatedCostUsd)}</td></tr>`).join('') || '<tr><td colspan="4">No recorded usage yet.</td></tr>'}</table>`;
  const totals = dashboard.totals;
  return `<!doctype html><html><head><meta charset="UTF-8"><style>body{font-family:var(--vscode-font-family);color:var(--vscode-foreground);padding:18px}section{display:flex;gap:20px;flex-wrap:wrap}.card{border:1px solid var(--vscode-panel-border);padding:12px;min-width:150px}table{border-collapse:collapse;width:100%;max-width:820px}td,th{padding:7px;border-bottom:1px solid var(--vscode-panel-border);text-align:left}.muted{color:var(--vscode-descriptionForeground)}</style></head><body><h1>Usage, Context and Cost</h1><section><div class="card"><strong>Total tokens</strong><br>${totals.inputTokens + totals.outputTokens}</div><div class="card"><strong>Context avoided</strong><br>${totals.contextAvoided}</div><div class="card"><strong>Provider-reported cost</strong><br>${currency(totals.providerReportedCostUsd)}</div><div class="card"><strong>LGS-estimated cost</strong><br>${currency(totals.estimatedCostUsd)}</div><div class="card"><strong>Cloud escalations</strong><br>${totals.cloudEscalations}</div></section><h2>Billing status</h2><section>${billing || '<p class="muted">No provider billing metadata recorded yet.</p>'}</section><h2>Context</h2><section>${context || '<p class="muted">Context utilization is shown when the request producer reports exact token counts.</p>'}</section>${dashboard.budget.warnings.map(warning => `<p class="muted">${escape(warning)}</p>`).join('')}${row('By model', dashboard.aggregates.model)}${row('By agent', dashboard.aggregates.agent)}${row('By task', dashboard.aggregates.task)}${row('By provider connection', dashboard.aggregates.provider)}<p class="muted">Local models are shown as local/not applicable for API monetary cost. This dashboard does not claim that local electricity or hardware has no real cost. Prompt and source contents are never stored for metrics.</p></body></html>`;
}
function escape(value: string): string { return value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character); }
