import { randomUUID } from 'node:crypto';
import type { StreamEvent, Usage } from '../model/types.js';
import type { UsageAggregate, UsageBillingKind, UsageConfiguration, UsageDashboard, UsageGroup, UsageRecord, PricingEntry } from './types.js';
import { FilePricingStore, FileUsageStore } from './store.js';
import { consumeActiveContextMetrics } from './runtime.js';

export type UsageRequest = Omit<UsageRecord, 'id' | 'timestamp' | 'billing' | 'providerReportedCostUsd' | 'estimatedCostUsd' | 'promptProcessingMs' | 'generationMs' | 'tokensPerSecond' | 'latencyMs' | 'inputTokens' | 'outputTokens' | 'cachedTokens' | 'reasoningTokens'> & { billing?: UsageBillingKind };

export class UsageTracker {
  constructor(private readonly store: FileUsageStore, private readonly pricing: FilePricingStore, private readonly configuration: UsageConfiguration) {}
  begin(request: UsageRequest): UsageMeasurement { return new UsageMeasurement(this.store, this.pricing.read(), { ...consumeActiveContextMetrics(), ...request }); }
  records(): UsageRecord[] { return this.store.read(); }
  cleanup(): number { return this.store.cleanup(this.configuration); }
  dashboard(task?: string, now = Date.now()): UsageDashboard { const records = this.records().filter(record => !task || record.task === task); const groups: UsageGroup[] = ['request', 'agent', 'task', 'session', 'model', 'provider', 'workspace', 'period']; const aggregates = Object.fromEntries(groups.map(group => [group, aggregate(records, group)])) as UsageDashboard['aggregates']; const cloud = records.filter(record => record.billing === 'commercial'); const period = cloud.filter(record => Date.parse(record.timestamp) >= now - this.configuration.budgets.periodDays * 86_400_000); const spend = (values: UsageRecord[]) => values.reduce((sum, record) => sum + (record.providerReportedCostUsd ?? record.estimatedCostUsd ?? 0), 0); const taskSpend = task ? spend(cloud) : undefined; const periodSpend = spend(period); const warnings = budgetWarnings(taskSpend, periodSpend, this.configuration);
    return { records, aggregates, totals: { key: 'all', ...combine(records) }, budget: { taskSpendUsd: taskSpend, periodSpendUsd: periodSpend, warnings } };
  }
  budgetDecision(task?: string): { allowed: boolean; warning?: string } { const dashboard = this.dashboard(task); const b = this.configuration.budgets; if (b.maxCloudSpendPerTask !== undefined && (dashboard.budget.taskSpendUsd ?? 0) >= b.maxCloudSpendPerTask) return { allowed: false, warning: 'Task cloud-spend budget is exhausted.' }; if (b.maxCloudSpendPerPeriod !== undefined && (dashboard.budget.periodSpendUsd ?? 0) >= b.maxCloudSpendPerPeriod) return { allowed: false, warning: 'Cloud-spend period budget is exhausted.' }; if (b.askBeforeCloudEscalation) return { allowed: false, warning: 'Cloud escalation requires user confirmation.' }; return { allowed: true }; }
}

export class UsageMeasurement {
  private readonly started = performance.now(); private firstToken?: number; private usage: Usage = {}; private ended = false;
  constructor(private readonly store: FileUsageStore, private readonly pricing: Record<string, PricingEntry>, private readonly request: UsageRequest) {}
  observe(event: StreamEvent): void { if (event.type === 'textDelta' && this.firstToken === undefined) this.firstToken = performance.now(); if (event.type === 'usage') this.usage = { ...this.usage, ...event.usage }; }
  finish(): UsageRecord | undefined { if (this.ended) return; this.ended = true; const end = performance.now(); const promptProcessingMs = this.firstToken === undefined ? undefined : rounded(this.firstToken - this.started); const generationMs = this.firstToken === undefined ? undefined : rounded(end - this.firstToken); const latencyMs = rounded(end - this.started); const output = this.usage.outputTokens; const entry = this.pricing[`${this.request.providerConnection}:${this.request.model}`] ?? this.pricing[this.request.providerConnection ?? '']; const billing = this.request.billing ?? entry?.billing ?? 'unknown'; const estimatedCostUsd = estimate(this.usage, entry); const record: UsageRecord = { id: randomUUID(), timestamp: new Date().toISOString(), ...this.request, inputTokens: this.usage.inputTokens, outputTokens: output, cachedTokens: this.usage.cachedTokens, reasoningTokens: this.usage.reasoningTokens, providerReportedCostUsd: this.usage.providerReportedCostUsd, estimatedCostUsd, promptProcessingMs, generationMs, latencyMs, tokensPerSecond: output !== undefined && generationMs && generationMs > 0 ? rounded(output / (generationMs / 1000)) : undefined, billing };
    this.store.append(stripUndefined(record)); return record;
  }
}

function estimate(usage: Usage, entry?: PricingEntry): number | undefined { if (!entry || entry.billing !== 'commercial') return; let cost = 0; let known = false; if (usage.inputTokens !== undefined && entry.inputPerMillionUsd !== undefined) { cost += usage.inputTokens * entry.inputPerMillionUsd / 1_000_000; known = true; } if (usage.cachedTokens !== undefined && entry.cachedInputPerMillionUsd !== undefined) { cost += usage.cachedTokens * entry.cachedInputPerMillionUsd / 1_000_000; known = true; } if (usage.outputTokens !== undefined && entry.outputPerMillionUsd !== undefined) { cost += usage.outputTokens * entry.outputPerMillionUsd / 1_000_000; known = true; } return known ? rounded(cost, 8) : undefined; }
function aggregate(records: UsageRecord[], group: UsageGroup): UsageAggregate[] { const values = new Map<string, UsageRecord[]>(); for (const record of records) { const key = group === 'request' ? record.id : group === 'provider' ? record.providerConnection ?? 'unknown' : group === 'period' ? record.timestamp.slice(0, 10) : record[group] ?? 'unknown'; values.set(key, [...(values.get(key) ?? []), record]); } return [...values.entries()].map(([key, records_]) => ({ key, ...combine(records_) })).sort((a, b) => b.inputTokens + b.outputTokens - a.inputTokens - a.outputTokens); }
function combine(records: UsageRecord[]): Omit<UsageAggregate, 'key'> { return records.reduce<Omit<UsageAggregate, 'key'>>((total, record) => ({ requests: total.requests + 1, inputTokens: total.inputTokens + (record.inputTokens ?? 0), outputTokens: total.outputTokens + (record.outputTokens ?? 0), cachedTokens: total.cachedTokens + (record.cachedTokens ?? 0), reasoningTokens: total.reasoningTokens + (record.reasoningTokens ?? 0), contextUtilized: total.contextUtilized + (record.contextUtilized ?? 0), contextAvoided: total.contextAvoided + (record.contextSavings?.tokensAvoided ?? 0), providerReportedCostUsd: total.providerReportedCostUsd + (record.providerReportedCostUsd ?? 0), estimatedCostUsd: total.estimatedCostUsd + (record.estimatedCostUsd ?? 0), totalLatencyMs: total.totalLatencyMs + (record.latencyMs ?? 0), totalGenerationMs: total.totalGenerationMs + (record.generationMs ?? 0), cloudEscalations: total.cloudEscalations + (record.role === 'cloudEscalation' ? 1 : 0) }), { requests: 0, inputTokens: 0, outputTokens: 0, cachedTokens: 0, reasoningTokens: 0, contextUtilized: 0, contextAvoided: 0, providerReportedCostUsd: 0, estimatedCostUsd: 0, totalLatencyMs: 0, totalGenerationMs: 0, cloudEscalations: 0 }); }
function budgetWarnings(task: number | undefined, period: number, config: UsageConfiguration): string[] { const warnings: string[] = []; const check = (value: number | undefined, limit: number | undefined, label: string) => { if (value === undefined || limit === undefined) return; if (value >= limit) warnings.push(`${label} budget exhausted.`); else if (value / limit * 100 >= config.budgets.warnAtPercent) warnings.push(`${label} budget is above the ${config.budgets.warnAtPercent}% warning threshold.`); }; check(task, config.budgets.maxCloudSpendPerTask, 'Task cloud-spend'); check(period, config.budgets.maxCloudSpendPerPeriod, 'Period cloud-spend'); return warnings; }
function rounded(value: number, decimals = 2): number { const p = 10 ** decimals; return Math.round(value * p) / p; }
function stripUndefined<T extends object>(value: T): T { return Object.fromEntries(Object.entries(value).filter(([, child]) => child !== undefined)) as T; }
