import { describe, expect, it } from 'vitest'; import * as fs from 'node:fs'; import * as os from 'node:os'; import * as path from 'node:path';
import { createDefaultRegistry } from '../src/settings/defaults.js'; import { resolveSetting } from '../src/settings/registry.js'; import { SettingsManager } from '../src/settings/configuration.js'; import { createBackends } from '../src/model/registry.js'; import { defaultProfiles } from '../src/model/profiles.js';
const context=()=>{const values:Record<string,unknown>={};return{values,globalState:{get:(key:string)=>values[key],update:async(key:string,value:unknown)=>{values[key]=value;}}} as never;};
describe('settings framework',()=>{
  it('resolves built-in, user, then workspace precedence',()=>{const def=createDefaultRegistry().get('models.defaultModel')!;expect(resolveSetting(def,{},{}).value).toBe('');expect(resolveSetting(def,{'models.defaultModel':'user-model'},{})).toMatchObject({value:'user-model',source:'user'});expect(resolveSetting(def,{'models.defaultModel':'user-model'},{'models.defaultModel':'workspace-model'})).toMatchObject({value:'workspace-model',source:'workspace'});});
  it('describes the three appearance modes with research-lab labels',()=>{const appearance=createDefaultRegistry().get('appearance.theme')!;expect(appearance.choices).toEqual([{value:'vscode',label:'Follow VS Code'},{value:'lgs-light',label:'Research Paper / Light'},{value:'lgs-dark',label:'Research Lab / Dark'}]);});
  it('does not register future-phase placeholder controls',()=>expect(createDefaultRegistry().all().some(item=>item.type==='placeholder')).toBe(false));
  it('persists user settings and workspace overrides',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'lgs-settings-'));const manager=new SettingsManager(context(),root);expect(await manager.set('computer.activityLogRetentionDays',42,'user')).toBeUndefined();expect(manager.userValues()['computer.activityLogRetentionDays']).toBe(42);expect(await manager.set('computer.activityLogRetentionDays',7,'workspace')).toBeUndefined();expect(manager.effective().find(x=>x.id==='computer.activityLogRetentionDays')).toMatchObject({value:7,source:'workspace'});expect(manager.workspaceConfiguration().computer.activityLogRetentionDays).toBe(7);fs.rmSync(root,{recursive:true,force:true});});
  it('keeps structured workspace computer policy authoritative over user settings',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'lgs-settings-'));fs.mkdirSync(path.join(root,'.lgs'));fs.writeFileSync(path.join(root,'.lgs','config.yaml'),'computer:\n  readOutsideWorkspace: deny\n');const manager=new SettingsManager(context(),root);expect(await manager.set('computer.readOutsideWorkspace','always_allow','user')).toBeUndefined();expect(manager.workspaceConfiguration().computer.readOutsideWorkspace).toBe('deny');fs.rmSync(root,{recursive:true,force:true});});
  it('reports malformed workspace YAML without throwing',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'lgs-settings-'));fs.mkdirSync(path.join(root,'.lgs'));fs.writeFileSync(path.join(root,'.lgs','config.yaml'),'settings: [broken');const manager=new SettingsManager(context(),root);expect(manager.errorsList().length).toBeGreaterThan(0);fs.rmSync(root,{recursive:true,force:true});});
  it('supports multiple independent connections using one adapter',()=>{const profiles=defaultProfiles().filter(x=>x.kind==='openai-compatible').map((x,i)=>({...x,id:'connection-'+i,name:'Connection '+i}));expect(createBackends(profiles,()=>undefined).size).toBe(2);expect(JSON.stringify(profiles)).not.toContain('apiKey');});
});
