import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { inflateRawSync } from 'node:zlib';
import { normalize } from './config.js';
import { ComputerPermissionResolver } from './permissions.js';
import type { ActivityLedgerEntry, AgentTrace, ComputerCommandRequest, ComputerCommandResult, ComputerConfiguration, ComputerPermissionPrompt, DecisionJournalEntry, ExternalAccess, ExternalFileContent } from './types.js';

const MAX_FILE_BYTES = 2 * 1024 * 1024;
const MAX_OUTPUT_BYTES = 256 * 1024;
const SECRET = /(password|secret|token|authorization|api[-_]?key|cookie)/i;

/** Validated, permission-gated computer operations. It never evaluates a shell string. */
export class ComputerAgent {
  readonly permissions: ComputerPermissionResolver;
  constructor(readonly workspaceRoot: string, readonly configuration: ComputerConfiguration, private readonly prompt?: ComputerPermissionPrompt) { this.permissions = new ComputerPermissionResolver(configuration, workspaceRoot); }
  async listPath(target: string): Promise<unknown[]> { await this.authorizePath(target, 'read', 'List external path'); const resolved = normalize(target); return fs.readdirSync(resolved, { withFileTypes: true }).slice(0, 1000).map(item => ({ name: item.name, path: path.join(resolved, item.name), type: item.isDirectory() ? 'directory' : item.isFile() ? 'file' : item.isSymbolicLink() ? 'symlink' : 'other' })); }
  async statPath(target: string): Promise<Record<string, unknown>> { await this.authorizePath(target, 'read', 'Inspect external path'); const stats = fs.statSync(normalize(target)); return { path: normalize(target), type: stats.isDirectory() ? 'directory' : stats.isFile() ? 'file' : 'other', size: stats.size, modifiedAt: stats.mtime.toISOString(), createdAt: stats.birthtime.toISOString(), mode: stats.mode.toString(8) }; }
  async readFile(target: string): Promise<ExternalFileContent> { await this.authorizePath(target, 'read', 'Read external document'); return extractExternalFile(normalize(target)); }
  async copy(source: string, destination: string): Promise<void> { await this.authorizePath(source, 'read', 'Copy external file'); await this.authorizePath(destination, 'write', 'Copy external file'); fs.copyFileSync(normalize(source), normalize(destination)); }
  async move(source: string, destination: string): Promise<void> { await this.authorizePath(source, 'write', 'Move external file'); await this.authorizePath(destination, 'write', 'Move external file'); fs.renameSync(normalize(source), normalize(destination)); }
  async createDirectory(target: string): Promise<void> { await this.authorizePath(target, 'write', 'Create external directory'); fs.mkdirSync(normalize(target), { recursive: true }); }
  async deleteFile(target: string): Promise<void> { await this.authorizePath(target, 'write', 'Delete external file'); const stats = fs.lstatSync(normalize(target)); if (stats.isDirectory()) throw new Error('delete_external_file only deletes files or symlinks, not directories.'); fs.unlinkSync(normalize(target)); }
  async findFiles(root: string, query: string, maxResults = 100): Promise<string[]> { await this.authorizePath(root, 'read', 'Find external files'); const term = query.toLowerCase(); const result: string[] = []; const visit = (current: string): void => { if (result.length >= maxResults) return; let entries: fs.Dirent[]; try { entries = fs.readdirSync(current, { withFileTypes: true }); } catch { return; } for (const entry of entries) { if (result.length >= maxResults) return; const child = path.join(current, entry.name); if (entry.isDirectory()) { if (!entry.isSymbolicLink() && !['node_modules', '.git'].includes(entry.name)) visit(child); } else if (entry.name.toLowerCase().includes(term)) result.push(child); } }; visit(normalize(root)); return result; }
  inspectSystem(): Record<string, unknown> { return { platform: process.platform, release: os.release(), architecture: process.arch, hostname: os.hostname(), home: os.homedir(), shell: process.env.SHELL ? path.basename(process.env.SHELL) : undefined }; }
  async runCommand(request: ComputerCommandRequest, signal = new AbortController().signal): Promise<ComputerCommandResult> {
    validateCommand(request); const cwd = normalize(request.cwd ?? this.workspaceRoot); if (!fs.statSync(cwd).isDirectory()) throw new Error('Command working directory must be an existing directory.');
    const decision = this.permissions.command(request.operation); const target = `${request.executable} ${request.args.join(' ')}`;
    if (!(await this.authorize(decision.policy, request.operation, target, request.reason, Boolean(request.dryRun ?? this.configuration.dryRun), decision.highRisk))) return commandResult(request, cwd, 'denied', '', '', null);
    if (request.dryRun ?? this.configuration.dryRun) return commandResult(request, cwd, 'planned', '', '', null);
    const started = new Date(); const id = randomUUID(); const environment: NodeJS.ProcessEnv = { PATH: process.env.PATH, HOME: process.env.HOME, LANG: process.env.LANG, ...request.env, LGS_COMPUTER_COMMAND: '1' };
    return await new Promise(resolve => { let child: ChildProcessWithoutNullStreams; try { child = spawn(request.executable, request.args, { cwd, env: environment, shell: false, windowsHide: !request.visible }); } catch (error) { resolve(commandResult(request, cwd, 'spawn_error', '', error instanceof Error ? error.message : 'Unable to spawn command.', null, id, started)); return; }
      let stdout = '', stderr = '', settled = false, timedOut = false; child.stdout.setEncoding('utf8'); child.stderr.setEncoding('utf8'); child.stdout.on('data', value => { stdout = append(stdout, String(value)); }); child.stderr.on('data', value => { stderr = append(stderr, String(value)); });
      const stop = (timeout: boolean) => { if (settled) return; timedOut = timeout; child.kill('SIGTERM'); setTimeout(() => { if (!settled) child.kill('SIGKILL'); }, 1000).unref(); }; const abort = () => stop(false); signal.addEventListener('abort', abort, { once: true }); const timer = setTimeout(() => stop(true), Math.min(request.timeoutMs ?? 120000, 1800000));
      child.on('error', error => { stderr = append(stderr, error.message); }); child.on('close', code => { settled = true; clearTimeout(timer); signal.removeEventListener('abort', abort); resolve(commandResult(request, cwd, timedOut ? 'timed_out' : signal.aborted ? 'cancelled' : code === 0 ? 'passed' : 'failed', stdout, stderr, code, id, started)); });
    });
  }
  async recordActivity(entry: Omit<ActivityLedgerEntry, 'id' | 'timestamp'>): Promise<ActivityLedgerEntry> { const complete = { ...entry, id: randomUUID(), timestamp: new Date().toISOString(), details: redact(entry.details) }; appendJsonl(path.join(this.workspaceRoot, '.lgs', 'activity-ledger.jsonl'), complete); return complete; }
  activities(taskId?: string, limit = 50): ActivityLedgerEntry[] { return readJsonl<ActivityLedgerEntry>(path.join(this.workspaceRoot, '.lgs', 'activity-ledger.jsonl')).filter(item => !taskId || item.taskId === taskId).slice(-Math.min(limit, 500)).reverse(); }
  recordTrace(trace: Omit<AgentTrace, 'updatedAt'>): AgentTrace { const complete = { ...trace, updatedAt: new Date().toISOString() }; const file = path.join(this.workspaceRoot, '.lgs', 'tasks', trace.taskId, 'agent-traces.json'); const all = readJson<AgentTrace[]>(file, []); const index = all.findIndex(item => item.agentId === trace.agentId); if (index >= 0) all[index] = complete; else all.push(complete); writeJson(file, all); return complete; }
  traces(taskId: string): AgentTrace[] { return readJson(path.join(this.workspaceRoot, '.lgs', 'tasks', taskId, 'agent-traces.json'), []); }
  journal(entry: Omit<DecisionJournalEntry, 'id' | 'timestamp'>): DecisionJournalEntry { const complete = { ...entry, id: randomUUID(), timestamp: new Date().toISOString() }; appendJsonl(path.join(this.workspaceRoot, '.lgs', 'tasks', entry.taskId, 'decision-journal.jsonl'), complete); return complete; }
  decisions(taskId: string, limit = 50): DecisionJournalEntry[] { return readJsonl<DecisionJournalEntry>(path.join(this.workspaceRoot, '.lgs', 'tasks', taskId, 'decision-journal.jsonl')).slice(-Math.min(limit, 500)).reverse(); }
  private async authorizePath(target: string, access: ExternalAccess, reason: string): Promise<void> { const decision = this.permissions.filesystem(target, access); if (!(await this.authorize(decision.policy, decision.operation, normalize(target), reason, false, decision.highRisk))) throw new Error('Computer operation was denied by policy.'); }
  private async authorize(policy: 'always_allow' | 'ask' | 'deny', operation: import('./types.js').ComputerOperationClass, target: string, reason: string, dryRun: boolean, highRisk: boolean): Promise<boolean> { if (policy === 'deny') return false; if (policy === 'always_allow' && !highRisk) return true; return Boolean(await this.prompt?.({ operation, target, reason, dryRun })); }
}
function validateCommand(request: ComputerCommandRequest): void { if (!request.executable || /[\0\r\n]/.test(request.executable) || !Array.isArray(request.args) || request.args.some(arg => typeof arg !== 'string' || arg.includes('\0'))) throw new Error('Computer commands require a safe executable and argument array.'); if (!request.reason?.trim()) throw new Error('Computer commands require a reason for the Activity Ledger.'); if (!Number.isInteger(request.timeoutMs ?? 120000) || (request.timeoutMs ?? 120000) < 1) throw new Error('Command timeout must be a positive integer.'); }
function commandResult(request: ComputerCommandRequest, cwd: string, status: ComputerCommandResult['status'], stdout: string, stderr: string, exitCode: number | null, id = randomUUID(), started = new Date()): ComputerCommandResult { const completed = new Date(); return { id, status, command: [request.executable, ...request.args].join(' '), operation: request.operation, cwd, exitCode, stdout, stderr, startedAt: started.toISOString(), completedAt: completed.toISOString(), durationMs: completed.getTime() - started.getTime() }; }
function append(value: string, next: string): string { return (value + next).slice(-MAX_OUTPUT_BYTES); }
function appendJsonl(file: string, value: unknown): void { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.appendFileSync(file, JSON.stringify(value) + '\n'); }
function readJsonl<T>(file: string): T[] { try { return fs.readFileSync(file, 'utf8').split('\n').flatMap(line => { try { return line ? [JSON.parse(line) as T] : []; } catch { return []; } }); } catch { return []; } }
function readJson<T>(file: string, fallback: T): T { try { return JSON.parse(fs.readFileSync(file, 'utf8')) as T; } catch { return fallback; } }
function writeJson(file: string, value: unknown): void { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n'); }
function redact(value: unknown): Record<string, unknown> | undefined { if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined; return Object.fromEntries(Object.entries(value as Record<string, unknown>).flatMap(([key, child]) => SECRET.test(key) ? [] : [[key, child]])); }

export function extractExternalFile(file: string): ExternalFileContent { const stats = fs.statSync(file); if (!stats.isFile()) throw new Error('External path is not a file.'); const extension = path.extname(file).toLowerCase(); const raw = fs.readFileSync(file); const truncated = raw.length > MAX_FILE_BYTES; const data = raw.subarray(0, MAX_FILE_BYTES); const base = { path: file, metadata: { size: stats.size, modifiedAt: stats.mtime.toISOString() }, truncated };
  if (['.txt', '.md', '.markdown', '.ts', '.tsx', '.js', '.jsx', '.py', '.java', '.c', '.cpp', '.cs', '.go', '.rs', '.yaml', '.yml', '.xml', '.html', '.css', '.json'].includes(extension)) { const text = data.toString('utf8'); if (extension === '.json') { try { return { ...base, format: 'json', text, structured: JSON.parse(text) }; } catch { /* Return source text with invalid JSON metadata. */ } } return { ...base, format: extension === '.md' || extension === '.markdown' ? 'markdown' : extension.match(/\.(ts|tsx|js|jsx|py|java|c|cpp|cs|go|rs|yaml|yml|xml|html|css)$/) ? 'source' : 'text', text }; }
  if (extension === '.csv') { const text = data.toString('utf8'); return { ...base, format: 'csv', text, structured: csv(text) }; }
  if (extension === '.pdf') return { ...base, format: 'pdf', text: pdfText(data) };
  if (extension === '.docx') { const entries = zipEntries(data); const text = entries.get('word/document.xml'); return { ...base, format: 'docx', text: text ? xmlText(text.toString('utf8')) : undefined, metadata: { ...base.metadata, parts: [...entries.keys()].filter(key => key.startsWith('word/')).length } }; }
  if (extension === '.xlsx') { const entries = zipEntries(data); const shared = entries.get('xl/sharedStrings.xml'); const strings = shared ? xmlText(shared.toString('utf8')).split('\n') : []; const sheets = [...entries.entries()].filter(([name]) => /^xl\/worksheets\/sheet\d+\.xml$/.test(name)).map(([name, content]) => ({ name: path.basename(name), rows: xlsxRows(content.toString('utf8'), strings) })); return { ...base, format: 'xlsx', structured: { sheets } }; }
  if (['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg'].includes(extension)) return { ...base, format: 'image', metadata: { ...base.metadata, ...imageMetadata(data, extension) } };
  return { ...base, format: 'unknown', metadata: { ...base.metadata, notice: 'Binary contents were not sent to a model.' } };
}
function csv(text: string): string[][] { return text.split(/\r?\n/).filter(Boolean).slice(0, 1000).map(line => line.match(/(?:^|,)(?:"((?:[^"]|"")*)"|([^",]*))/g)?.map(value => value.replace(/^,?"?|"?$/g, '').replaceAll('""', '"')) ?? [line]); }
function pdfText(data: Buffer): string { return [...data.toString('latin1').matchAll(/\(([^()]{1,1000})\)/g)].map(match => match[1].replace(/\\[nrt]/g, ' ')).join('\n').slice(0, MAX_FILE_BYTES); }
function xmlText(value: string): string { return value.replace(/<w:tab\s*\/>/g, '\t').replace(/<w:br\s*\/>/g, '\n').replace(/<\/w:p>/g, '\n').replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').trim(); }
function zipEntries(data: Buffer): Map<string, Buffer> { const entries = new Map<string, Buffer>(); for (let index = 0; index + 30 < data.length; index++) { if (data.readUInt32LE(index) !== 0x04034b50) continue; const method = data.readUInt16LE(index + 8); const compressed = data.readUInt32LE(index + 18); const nameLength = data.readUInt16LE(index + 26); const extra = data.readUInt16LE(index + 28); const name = data.subarray(index + 30, index + 30 + nameLength).toString('utf8'); const start = index + 30 + nameLength + extra; if (!name || start + compressed > data.length) continue; const payload = data.subarray(start, start + compressed); try { entries.set(name, method === 0 ? payload : method === 8 ? inflateRawSync(payload) : Buffer.alloc(0)); } catch { /* Skip malformed archive entry. */ } index = start + compressed - 1; } return entries; }
function xlsxRows(xml: string, shared: string[]): string[][] { const rows: string[][] = []; for (const row of xml.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)) { const values: string[] = []; for (const cell of row[1].matchAll(/<c(?:[^>]*)?(?: t="(s)")?[^>]*>([\s\S]*?)<\/c>/g)) { const value = cell[2].match(/<v>([\s\S]*?)<\/v>/)?.[1] ?? ''; values.push(cell[1] === 's' ? shared[Number(value)] ?? '' : value); } rows.push(values); } return rows.slice(0, 1000); }
function imageMetadata(data: Buffer, extension: string): Record<string, unknown> { if (extension === '.png' && data.length >= 24) return { width: data.readUInt32BE(16), height: data.readUInt32BE(20) }; if ((extension === '.jpg' || extension === '.jpeg') && data.length > 10) for (let index = 2; index + 9 < data.length; index++) if (data[index] === 0xff && data[index + 1] >= 0xc0 && data[index + 1] <= 0xc3) return { height: data.readUInt16BE(index + 5), width: data.readUInt16BE(index + 7) }; return {}; }
