import { ComputerAgent } from './agent.js';
import { COMPUTER_OPERATION_CLASSES, type ComputerCommandRequest, type DecisionJournalEntry } from './types.js';
import { TASK_PROFILES } from '../watchdog/types.js';
import { ToolRegistry, toolError } from '../tools/framework.js';
import { ToolFailure, type ToolPermission } from '../tools/types.js';
import type { FileTaskStateStore } from '../watchdog/state.js';

const READ: ToolPermission = { access: 'read-only', scope: 'computer', network: false, category: 'read-only' };
const WRITE: ToolPermission = { access: 'execute', scope: 'computer', network: false, category: 'dangerous' };
const COMMAND: ToolPermission = { access: 'execute', scope: 'computer', network: false, category: 'process' };
const pathProperty = { type: 'string' as const, minLength: 1, maxLength: 4096 };

export function registerComputerTools(registry: ToolRegistry, agent: ComputerAgent, tasks?: FileTaskStateStore): ToolRegistry {
  registry.register({ id: 'list_path', description: 'List a permission-approved external directory without reading file contents.', permission: READ, argumentSchema: object({ path: pathProperty }, ['path']), execute: async args => ({ data: await agent.listPath(args.path as string), source: 'filesystem' }) });
  registry.register({ id: 'stat_path', description: 'Inspect metadata for a permission-approved external path.', permission: READ, argumentSchema: object({ path: pathProperty }, ['path']), execute: async args => ({ data: await agent.statPath(args.path as string), source: 'filesystem' }) });
  registry.register({ id: 'read_external_file', description: 'Extract external document content deterministically. Binary bytes are never returned as model context.', permission: READ, argumentSchema: object({ path: pathProperty }, ['path']), execute: async args => ({ data: await agent.readFile(args.path as string), source: 'filesystem' }) });
  registry.register({ id: 'find_external_files', description: 'Find matching filenames under a permission-approved external directory.', permission: READ, argumentSchema: object({ root: pathProperty, query: { type: 'string', minLength: 1, maxLength: 300 }, maxResults: { type: 'integer', minimum: 1, maximum: 1000 } }, ['root', 'query']), execute: async args => { const data = await agent.findFiles(args.root as string, args.query as string, args.maxResults as number | undefined); return { data, resultCount: data.length, source: 'filesystem' }; } });
  registry.register({ id: 'copy_external_file', description: 'Copy one external user-owned file after write approval.', permission: WRITE, argumentSchema: object({ source: pathProperty, destination: pathProperty }, ['source', 'destination']), execute: async args => { await agent.copy(args.source as string, args.destination as string); return { data: { copied: true }, source: 'computer' }; } });
  registry.register({ id: 'move_external_file', description: 'Move one external user-owned file after write approval.', permission: WRITE, argumentSchema: object({ source: pathProperty, destination: pathProperty }, ['source', 'destination']), execute: async args => { await agent.move(args.source as string, args.destination as string); return { data: { moved: true }, source: 'computer' }; } });
  registry.register({ id: 'create_external_directory', description: 'Create an external directory after write approval.', permission: WRITE, argumentSchema: object({ path: pathProperty }, ['path']), execute: async args => { await agent.createDirectory(args.path as string); return { data: { created: true }, source: 'computer' }; } });
  registry.register({ id: 'delete_external_file', description: 'Delete a single external file after explicit destructive-action approval; directories are rejected.', permission: WRITE, argumentSchema: object({ path: pathProperty }, ['path']), execute: async args => { await agent.deleteFile(args.path as string); return { data: { deleted: true }, source: 'computer' }; } });
  registry.register({ id: 'inspect_computer', description: 'Read OS, release, and architecture for software setup planning.', permission: READ, argumentSchema: object({}, []), execute: () => ({ data: agent.inspectSystem(), source: 'computer' }) });
  registry.register({ id: 'run_computer_command', description: 'Run a validated executable plus argument array outside the workspace only after policy approval. It supports cwd, environment, timeout, cancellation, visibility, and dry run; it never runs a shell string.', permission: COMMAND, argumentSchema: object({ executable: { type: 'string', minLength: 1, maxLength: 1024 }, args: { type: 'array', items: { type: 'string', maxLength: 4096 }, maxItems: 200 }, cwd: pathProperty, env: { type: 'object', properties: {}, additionalProperties: true }, timeoutMs: { type: 'integer', minimum: 1, maximum: 1800000 }, operation: { type: 'string', enum: [...COMPUTER_OPERATION_CLASSES] }, reason: { type: 'string', minLength: 1, maxLength: 2000 }, visible: { type: 'boolean' }, dryRun: { type: 'boolean' } }, ['executable', 'args', 'operation', 'reason']), execute: async (args, context) => { const result = await agent.runCommand({ ...args, taskId: context.taskId } as ComputerCommandRequest, context.signal); await agent.recordActivity({ taskId: context.taskId, agent: context.agentId, model: context.model, operation: 'run_computer_command', target: result.command, reason: args.reason as string, permission: result.status === 'denied' ? 'deny' : 'ask', result: result.status, durationMs: result.durationMs, details: { cwd: result.cwd, exitCode: result.exitCode, dryRun: Boolean(args.dryRun) } }); return { data: result, source: 'computer' }; } });
  registry.register({ id: 'get_activity_ledger', description: 'Retrieve a compact, targeted view of durable computer activity rather than injecting complete logs into context.', permission: READ, argumentSchema: object({ taskId: { type: 'string', minLength: 1, maxLength: 128 }, limit: { type: 'integer', minimum: 1, maximum: 500 } }, []), execute: args => { const data = agent.activities(args.taskId as string | undefined, args.limit as number | undefined); return { data, resultCount: data.length, source: 'activity-ledger' }; } });
  registry.register({ id: 'record_decision', description: 'Record a concise, evidence-backed decision summary. It deliberately does not request private chain-of-thought.', permission: COMMAND, argumentSchema: object({ decision: { type: 'string', minLength: 1, maxLength: 2000 }, conclusion: { type: 'string', minLength: 1, maxLength: 4000 }, evidence: { type: 'array', items: { type: 'string', maxLength: 2000 }, minItems: 1, maxItems: 20 }, alternatives: { type: 'array', items: { type: 'string', maxLength: 1000 }, maxItems: 10 }, rejectedAlternatives: { type: 'array', items: { type: 'string', maxLength: 1000 }, maxItems: 10 }, confidence: { type: 'string', enum: ['low', 'medium', 'high'] }, externalSources: { type: 'array', items: { type: 'string', maxLength: 2000 }, maxItems: 20 } }, ['decision', 'conclusion', 'evidence', 'confidence']), execute: (args, context) => { if (!context.taskId) throw new ToolFailure(toolError('invalid_request', 'Decision Journal entries require a task ID.')); const data = agent.journal({ ...args, taskId: context.taskId, agent: context.agentId, model: context.model } as Omit<DecisionJournalEntry, 'id' | 'timestamp'>); return { data, resultCount: 1, source: 'decision-journal' }; } });
  registry.register({ id: 'get_decision_journal', description: 'Retrieve concise durable decision summaries for the active task.', permission: READ, argumentSchema: object({ limit: { type: 'integer', minimum: 1, maximum: 500 } }, []), execute: (_args, context) => { if (!context.taskId) throw new ToolFailure(toolError('invalid_request', 'Decision Journal requires a task ID.')); const data = agent.decisions(context.taskId); return { data, resultCount: data.length, source: 'decision-journal' }; } });
  registry.register({ id: 'set_task_profile', description: 'Set the task profile so Definition of Done does not impose repository documentation or Git commits on system, research, browser, or document work.', permission: COMMAND, argumentSchema: object({ profile: { type: 'string', enum: [...TASK_PROFILES] } }, ['profile']), execute: (args, context) => { if (!context.taskId || !tasks) throw new ToolFailure(toolError('invalid_request', 'Task profile requires task state.')); const data = tasks.update(context.taskId, { profile: args.profile as typeof TASK_PROFILES[number] }); return { data, resultCount: 1, source: 'computer' }; } });
  return registry;
}
function object(properties: Record<string, import('../tools/types.js').JsonSchema>, required: string[]) { return { type: 'object' as const, properties, required, additionalProperties: false }; }
