import { ToolRegistry, toolError } from '../tools/framework.js';
import { ToolFailure, type ToolPermission } from '../tools/types.js';
import type { ManagedProcessManager } from './processes.js';
import type { RuntimeVerifier, FileRuntimeStore } from './service.js';

const EXECUTE: ToolPermission = { access: 'execute', scope: 'workspace', network: true, category: 'process' };
const READ: ToolPermission = { access: 'read-only', scope: 'workspace', network: false, category: 'read-only' };
export function registerRuntimeTools(registry: ToolRegistry, processes: ManagedProcessManager, verifier: RuntimeVerifier, store: FileRuntimeStore): ToolRegistry {
  registry.register({ id: 'start_runtime', description: 'Start the configured application as an LGS-owned managed process. Only LGS-owned processes can later be stopped.', permission: EXECUTE, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async (_args, context) => ({ data: await verifier.start(context.taskId), resultCount: 1, source: 'execution' }) });
  registry.register({ id: 'stop_runtime', description: 'Stop one LGS-owned managed process by its LGS process ID. This never kills a discovered external PID.', permission: EXECUTE, argumentSchema: { type: 'object', properties: { processId: { type: 'string', minLength: 1, maxLength: 128 } }, required: ['processId'], additionalProperties: false }, execute: args => { const record = processes.stop(args.processId as string); if (!record) throw new ToolFailure(toolError('not_found', 'Managed process was not found or is not owned by LGS.')); return { data: record, resultCount: 1, source: 'execution' }; } });
  registry.register({ id: 'get_runtime_status', description: 'Read LGS-owned managed process state and the latest task runtime verification.', permission: READ, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: (_args, context) => ({ data: { processes: processes.list(context.taskId), verification: context.taskId ? store.latest(context.taskId) : undefined }, resultCount: processes.list(context.taskId).length, source: 'execution' }) });
  registry.register({ id: 'run_runtime_verification', description: 'Run configured startup, healthcheck, and optional browser acceptance checks. Persist concise results and raw artifacts for Debugger.', permission: EXECUTE, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async (_args, context) => { if (!context.taskId) throw new ToolFailure(toolError('invalid_request', 'Runtime verification requires a task ID.')); const data = await verifier.verify(context.taskId); return { data, resultCount: data.checks.length, source: 'execution' }; } });
  registerBrowser(registry, verifier); return registry;
}
function registerBrowser(registry: ToolRegistry, verifier: RuntimeVerifier): void {
  registry.register({ id: 'browser_open', description: 'Open a URL in the isolated Playwright browser session.', permission: EXECUTE, argumentSchema: { type: 'object', properties: { url: { type: 'string', minLength: 1, maxLength: 4096 } }, required: ['url'], additionalProperties: false }, execute: async args => ({ data: await verifier.browser.open(args.url as string), resultCount: 1, source: 'execution' }) });
  registry.register({ id: 'browser_click', description: 'Click a CSS or Playwright selector in the browser session.', permission: EXECUTE, argumentSchema: selectorSchema(), execute: async args => { await verifier.browser.click(args.selector as string); return { data: { clicked: args.selector }, resultCount: 1, source: 'execution' }; } });
  registry.register({ id: 'browser_type', description: 'Fill an input using a selector and text.', permission: EXECUTE, argumentSchema: { type: 'object', properties: { selector: { type: 'string', minLength: 1, maxLength: 1000 }, text: { type: 'string', maxLength: 10_000 } }, required: ['selector', 'text'], additionalProperties: false }, execute: async args => { await verifier.browser.type(args.selector as string, args.text as string); return { data: { typed: true }, resultCount: 1, source: 'execution' }; } });
  registry.register({ id: 'browser_get_text', description: 'Get rendered text for a selector.', permission: READ, argumentSchema: selectorSchema(), execute: async args => ({ data: { text: await verifier.browser.getText(args.selector as string) }, resultCount: 1, source: 'execution' }) });
  registry.register({ id: 'browser_wait_for', description: 'Wait for a selector, text, or idle browser state.', permission: EXECUTE, argumentSchema: { type: 'object', properties: { selector: { type: 'string', minLength: 1, maxLength: 1000 }, text: { type: 'string', minLength: 1, maxLength: 10_000 }, timeoutMs: { type: 'integer', minimum: 1, maximum: 300000 } }, additionalProperties: false }, validate: args => !args.selector && !args.text ? ['Specify selector or text.'] : [], execute: async args => { await verifier.browser.waitFor({ selector: args.selector as string | undefined, text: args.text as string | undefined, timeoutMs: args.timeoutMs as number | undefined }); return { data: { ready: true }, resultCount: 1, source: 'execution' }; } });
  registry.register({ id: 'browser_screenshot', description: 'Capture a full-page screenshot as a retained runtime artifact.', permission: EXECUTE, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: async () => ({ data: await verifier.browser.screenshot(), resultCount: 1, source: 'execution' }) });
  registry.register({ id: 'browser_console', description: 'Read browser console error events.', permission: READ, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: () => { const data = verifier.browser.consoleErrors(); return { data, resultCount: data.length, source: 'execution' }; } });
  registry.register({ id: 'browser_network_errors', description: 'Read failed browser network requests.', permission: READ, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: () => { const data = verifier.browser.networkErrors(); return { data, resultCount: data.length, source: 'execution' }; } });
}
function selectorSchema() { return { type: 'object' as const, properties: { selector: { type: 'string' as const, minLength: 1, maxLength: 1000 } }, required: ['selector'], additionalProperties: false }; }
