import type { CompletionViewState } from '../completion/types.js';

export type ChatOptions={thinking:'off'|'low'|'medium'|'high';approval:'always'|'on-request'|'never'};
export type TaskActivity={label:string;detail:string;status:'active'|'completed'|'warning';at:string};
export type TaskDashboard={taskId:string;objective:string;acceptanceCriteria:string[];plan:string[];completed:string[];remaining:string[];files:string[];completion?:CompletionViewState;advisor:{profile:string;model:string};agents:{role:string;model:string;profile:string;state:string}[];activities:TaskActivity[];usage:{context:number;contextMaximum?:number;tokens:number;tokensPerSecond?:number;cost:number};git:{modified:number;commit?:string};review:{findings:number;status?:string};};
export type ClientMessage={type:'userMessage';text:string}|{type:'cancel'}|{type:'selectProfile';profileId:string}|{type:'selectModel';model:string}|{type:'setOptions';options:ChatOptions}|{type:'listModels'}|{type:'newChat'}|{type:'openSettings'}|{type:'loadChat';chatId:string}|{type:'taskAction';action:'pause'|'approve'|'reject'|'retry'|'escalate'|'viewDiff'|'openFile'|'viewLogs'|'viewResearch'|'viewTaskState'};
export type HostMessage={type:'profiles';profiles:{id:string;name:string;kind:string}[];selected:string}|{type:'models';models:{id:string;displayName?:string}[];selected:string}|{type:'state';state:string}|{type:'streamStart';backend:string;model:string}|{type:'textDelta';text:string}|{type:'streamEnd'}|{type:'chatList';chats:{id:string;title:string;updatedAt:number}[]}|{type:'chatLoaded';messages:{role:'user'|'assistant'|'system';text:string}[]}|{type:'options';options:ChatOptions}|{type:'error';message:string}|{type:'appearance';theme:'vscode'|'lgs-light'|'lgs-dark'}|{type:'completionState';state:CompletionViewState}|{type:'taskDashboard';dashboard:TaskDashboard};
export function parseClientMessage(v:unknown):ClientMessage|undefined{if(typeof v!=='object'||v===null||Array.isArray(v))return;const x=v as Record<string,unknown>;if(x.type==='cancel'||x.type==='listModels'||x.type==='newChat'||x.type==='openSettings')return{type:x.type};if(x.type==='taskAction'&&['pause','approve','reject','retry','escalate','viewDiff','openFile','viewLogs','viewResearch','viewTaskState'].includes(String(x.action)))return{type:'taskAction',action:x.action as Extract<ClientMessage,{type:'taskAction'}>['action']};if(x.type==='userMessage'&&typeof x.text==='string'){const text=x.text.trim();return text&&text.length<=4000?{type:'userMessage',text}:undefined;}if((x.type==='selectProfile'||x.type==='selectModel'||x.type==='loadChat')&&typeof x[x.type==='selectProfile'?'profileId':x.type==='selectModel'?'model':'chatId']==='string'){const k=x.type==='selectProfile'?'profileId':x.type==='selectModel'?'model':'chatId';return x.type==='selectProfile'?{type:'selectProfile',profileId:x[k] as string}:x.type==='selectModel'?{type:'selectModel',model:x[k] as string}:{type:'loadChat',chatId:x[k] as string};}if(x.type==='setOptions'&&typeof x.options==='object'&&x.options!==null){const o=x.options as Record<string,unknown>;if(['off','low','medium','high'].includes(String(o.thinking))&&['always','on-request','never'].includes(String(o.approval)))return{type:'setOptions',options:{thinking:o.thinking as ChatOptions['thinking'],approval:o.approval as ChatOptions['approval']}};}}
export function isHostMessage(v:unknown):v is HostMessage{if(typeof v!=='object'||v===null||Array.isArray(v))return false;return ['profiles','models','state','streamStart','textDelta','streamEnd','chatList','chatLoaded','options','error','appearance','completionState','taskDashboard'].includes(String((v as Record<string,unknown>).type));}
