import type { SkillCreateInput, WorkspaceSkill } from '../knowledge/types.js';
import type { WorkspaceSkillStore } from '../knowledge/skills.js';

export type SkillGenerationAnswers = { work?: string; desiredExamples?: string; avoid?: string; priorities?: string; constraints?: string; scope?: 'project' | 'global'; profiles?: string[]; activation?: 'automatic' | 'manual' };
export type SkillGenerationDraft = { id: string; skillName?: string; answers: SkillGenerationAnswers; existing?: WorkspaceSkill; patterns: string[]; proposal?: SkillCreateInput; status: 'interview' | 'review' | 'approved' };

export class SkillGenerationService {
  private drafts = new Map<string, SkillGenerationDraft>();
  start(id: string, existing?: WorkspaceSkill): SkillGenerationDraft { const draft: SkillGenerationDraft = { id, existing, skillName: existing?.name, answers: existing ? { work: existing.description, desiredExamples: existing.content, scope: existing.scope, profiles: existing.routing?.profiles, activation: existing.routing?.activation } : {}, patterns: [], status: 'interview' }; this.drafts.set(id, draft); return clone(draft); }
  answer(id: string, answers: Partial<SkillGenerationAnswers> & { skillName?: string }): SkillGenerationDraft { const current = this.require(id); const next = { ...current, skillName: answers.skillName?.trim() || current.skillName, answers: { ...current.answers, ...answers } }; next.patterns = inferPatterns(next.answers); next.proposal = complete(next) ? proposal(next) : undefined; next.status = next.proposal ? 'review' : 'interview'; this.drafts.set(id, next); return clone(next); }
  nextQuestion(id: string): string | undefined { const draft = this.require(id); if (!draft.skillName) return 'What should this skill be called?'; if (!draft.answers.work) return 'What kind of work should this skill improve?'; if (!draft.answers.desiredExamples) return 'Describe examples of the behavior or output you want.'; if (!draft.answers.avoid) return 'What should the agent avoid?'; if (!draft.answers.priorities) return 'Which priorities or tradeoffs matter most?'; if (!draft.answers.constraints) return 'What environment or tooling constraints should it respect?'; if (!draft.answers.scope) return 'Should this skill be project-scoped or global?'; if (!draft.answers.activation) return 'Should matching tasks load it automatically, or only after manual activation?'; }
  approve(id: string, store: WorkspaceSkillStore): WorkspaceSkill { const draft = this.require(id); if (!draft.proposal || draft.status !== 'review') throw new Error('Review a complete skill proposal before approval.'); const skill = draft.existing ? store.updateInstructions(draft.existing.name, draft.existing.scope, draft.proposal.description, draft.proposal.instructions, draft.proposal.routing) : store.create(draft.proposal); this.drafts.set(id, { ...draft, status: 'approved' }); return skill; }
  diff(id: string): string { const draft = this.require(id); if (!draft.proposal) throw new Error('No skill proposal is ready.'); const before = draft.existing?.content || ''; const after = draft.proposal.instructions; return simpleDiff(before, after); }
  read(id: string): SkillGenerationDraft | undefined { const value = this.drafts.get(id); return value ? clone(value) : undefined; }
  private require(id: string): SkillGenerationDraft { const value = this.drafts.get(id); if (!value) throw new Error('Skill generation session not found.'); return value; }
}

function complete(value: SkillGenerationDraft): boolean { return Boolean(value.skillName && value.answers.work && value.answers.desiredExamples && value.answers.avoid && value.answers.priorities && value.answers.constraints && value.answers.scope && value.answers.activation); }
function inferPatterns(value: SkillGenerationAnswers): string[] { return [value.priorities && `Prioritize ${sentence(value.priorities)}`, value.avoid && `Avoid ${sentence(value.avoid)}`, value.constraints && `Respect ${sentence(value.constraints)}`].filter((item): item is string => Boolean(item)); }
function proposal(value: SkillGenerationDraft): SkillCreateInput { const answers = value.answers; const desired = value.existing ? `${value.existing.content.trim()}\n\n## Approved refinement\n\n${answers.desiredExamples!.trim()}` : `# Working pattern\n\n${answers.desiredExamples!.trim()}`; return { name: value.skillName!, description: answers.work!, scope: answers.scope, routing: { profiles: answers.profiles || [], activation: answers.activation! }, instructions: `${desired}\n\n## Priorities\n\n${bullet(answers.priorities!)}\n\n## Avoid\n\n${bullet(answers.avoid!)}\n\n## Constraints\n\n${bullet(answers.constraints!)}` }; }
function sentence(value: string): string { return value.trim().replace(/[.]+$/, '').slice(0, 240); }
function bullet(value: string): string { return value.split(/\r?\n|;/).map(item => item.trim()).filter(Boolean).map(item => `- ${item}`).join('\n'); }
function simpleDiff(before: string, after: string): string { const oldLines = before.trim().split('\n'); const newLines = after.trim().split('\n'); return ['--- current/SKILL.md', '+++ proposed/SKILL.md', ...oldLines.map(line => `-${line}`), ...newLines.map(line => `+${line}`)].join('\n'); }
function clone<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T; }
