import * as fs from 'node:fs';
import * as path from 'node:path';
import { ToolFailure, type ToolPermission } from '../tools/types.js';
import { ToolRegistry, toolError } from '../tools/framework.js';
import type { RepositoryIndex } from '../intelligence/indexer.js';
import { ContextBroker } from './broker.js';
import type { ContextLifecycleManager } from './lifecycle.js';

const READ: ToolPermission = { access: 'read-only', scope: 'workspace', network: false, category: 'read-only' };
export function registerContextTools(registry: ToolRegistry, broker: ContextBroker, lifecycle?: ContextLifecycleManager): ToolRegistry {
  registry.register({ id: 'select_context', description: 'Select deduplicated, retrieval-first repository context under a token budget. It returns hierarchy metadata and exact requested source ranges, never a blind summary.', permission: READ, argumentSchema: { type: 'object', properties: { objective: { type: 'string', minLength: 1, maxLength: 4000 }, tokenBudget: { type: 'integer', minimum: 1, maximum: 100000 }, paths: { type: 'array', maxItems: 50, items: { type: 'string', minLength: 1, maxLength: 1024 } }, symbols: { type: 'array', maxItems: 50, items: { type: 'string', minLength: 1, maxLength: 200 } } }, required: ['objective', 'tokenBudget'], additionalProperties: false }, execute: (args, context) => { const index = loadIndex(context.workspaceRoot); const paths = args.paths as string[] | undefined; const symbols = args.symbols as string[] | undefined; const candidates = broker.repositoryCandidates(context.workspaceRoot, index, { objective: args.objective as string, paths, symbols }); const selection = broker.select({ objective: args.objective as string, tokenBudget: args.tokenBudget as number, candidates, requestedPaths: paths, requestedSymbols: symbols }); return { data: selection, resultCount: selection.selected.length, truncated: selection.omitted.length > 0, source: 'repository-index' }; } });
  if (lifecycle) registerLifecycleTools(registry, lifecycle);
  return registry;
}
function registerLifecycleTools(registry: ToolRegistry, lifecycle: ContextLifecycleManager): void {
  const LIST = { type: 'array' as const, maxItems: 100, items: { type: 'string' as const, minLength: 1, maxLength: 1000 } };
  registry.register({ id: 'get_context_lifecycle', description: 'Read context pressure, compaction, rotation, and persistent task-knowledge metrics without exposing hidden reasoning.', permission: READ, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: (_args, context) => { if (!context.taskId) throw new ToolFailure(toolError('invalid_request', 'A task ID is required.')); return { data: lifecycle.read(context.taskId), resultCount: lifecycle.read(context.taskId) ? 1 : 0, source: 'execution' }; } });
  registry.register({ id: 'checkpoint_context', description: 'Persist the required durable task knowledge before rotating a disposable model context.', permission: { access: 'execute', scope: 'workspace', network: false, category: 'process' }, argumentSchema: { type: 'object', properties: { establishedFacts: LIST, decisions: LIST, currentHypothesis: { type: 'string', minLength: 1, maxLength: 4000 }, experimentState: { type: 'string', minLength: 1, maxLength: 4000 }, modifiedFiles: LIST, failedApproaches: LIST, unresolvedQuestions: LIST, acceptanceStatus: LIST, nextRecommendedAction: { type: 'string', minLength: 1, maxLength: 4000 } }, required: ['establishedFacts', 'decisions', 'currentHypothesis', 'experimentState', 'modifiedFiles', 'failedApproaches', 'unresolvedQuestions', 'acceptanceStatus', 'nextRecommendedAction'], additionalProperties: false }, execute: (args, context) => { if (!context.taskId || !context.sessionId) throw new ToolFailure(toolError('invalid_request', 'Task and session IDs are required.')); const data = lifecycle.checkpoint(context.taskId, { taskId: context.taskId, sessionId: context.sessionId, createdAt: new Date().toISOString(), establishedFacts: args.establishedFacts as string[], decisions: args.decisions as string[], currentHypothesis: args.currentHypothesis as string, experimentState: args.experimentState as string, modifiedFiles: args.modifiedFiles as string[], failedApproaches: args.failedApproaches as string[], unresolvedQuestions: args.unresolvedQuestions as string[], acceptanceStatus: args.acceptanceStatus as string[], nextRecommendedAction: args.nextRecommendedAction as string }); return { data, resultCount: 1, source: 'execution' }; } });
  registry.register({ id: 'rotate_context', description: 'Rotate to a fresh logical session after a validated checkpoint and return minimal reconstruction context. This does not complete the task.', permission: { access: 'execute', scope: 'workspace', network: false, category: 'process' }, argumentSchema: { type: 'object', properties: { freshSessionId: { type: 'string', minLength: 1, maxLength: 128 } }, required: ['freshSessionId'], additionalProperties: false }, execute: (args, context) => { if (!context.taskId) throw new ToolFailure(toolError('invalid_request', 'A task ID is required.')); const state = lifecycle.rotate(context.taskId, args.freshSessionId as string); return { data: { state, reconstruction: lifecycle.reconstruct(context.taskId) }, resultCount: 1, source: 'execution' }; } });
}
function loadIndex(root: string): RepositoryIndex { try { return JSON.parse(fs.readFileSync(path.join(root, '.lgs', 'index.json'), 'utf8')) as RepositoryIndex; } catch { throw new ToolFailure(toolError('not_found', 'Repository index not found. Run LGS: Rebuild Repository Index.')); } }
