import * as vscode from 'vscode'; import {parseClientMessage,type HostMessage} from './shared/messages.js'; import {Logger} from './shared/logger.js'; import {createBackends,type BackendId} from './model/registry.js'; import {textMessage,type LgsMessage} from './model/types.js'; import type {ModelBackend} from './model/backend.js';
export function activate(context:vscode.ExtensionContext):void { const logger=new Logger('LGS'); const provider=new LgsViewProvider(context,logger); context.subscriptions.push(vscode.window.registerWebviewViewProvider('lgs.sidebar',provider),vscode.commands.registerCommand('lgs.open',()=>vscode.commands.executeCommand('workbench.view.extension.lgs'))); logger.info('Extension activated'); } export function deactivate():void{}
class LgsViewProvider implements vscode.WebviewViewProvider { private view?:vscode.WebviewView; private backends:ModelBackend[]=[]; private backendId:BackendId='ollama'; private model=''; private history:LgsMessage[]=[]; private abort?:AbortController; private secrets=new Map<string,string>(); constructor(private context:vscode.ExtensionContext,private logger:Logger){}
async resolveWebviewView(view:vscode.WebviewView){this.view=view; for (const id of ['openai-compatible','anthropic'] as const) { const secret=await this.context.secrets.get('lgs.'+id); if (secret) this.secrets.set(id,secret); } this.backends=createBackends(id=>this.secrets.get(id)); view.webview.options={enableScripts:true,localResourceRoots:[this.context.extensionUri]}; view.webview.html=getHtml(view.webview,this.context.extensionUri); view.webview.onDidReceiveMessage((raw:unknown)=>void this.receive(raw),undefined,this.context.subscriptions); this.send({type:'state',state:'disconnected'});}
private current(){return this.backends.find(x=>x.id===this.backendId)!;} private send(m:HostMessage){void this.view?.webview.postMessage(m);}
private async receive(raw:unknown){const m=parseClientMessage(raw);if(!m){this.send({type:'error',message:'Invalid message.'});return;}if(m.type==='cancel'){this.abort?.abort();return;}if(m.type==='selectBackend'){if(m.backendId==='anthropic'&&!this.secrets.has('anthropic')){const secret=await vscode.window.showInputBox({prompt:'Anthropic API key (stored securely in VS Code SecretStorage)',password:true,ignoreFocusOut:true});if(!secret)return;await this.context.secrets.store('lgs.anthropic',secret);this.secrets.set('anthropic',secret);this.backends=createBackends(id=>this.secrets.get(id));}if(this.backends.some(x=>x.id===m.backendId))this.backendId=m.backendId as BackendId;this.model='';await this.listModels();return;}if(m.type==='listModels'){await this.listModels();return;}if(m.type==='userMessage'){if(!this.model){await this.listModels();if(!this.model){this.send({type:'error',message:'Select a model first.'});return;}}this.history.push(textMessage('user',m.text));await this.generate();}}
private async listModels(){const b=this.current();this.send({type:'state',state:'connecting'});try{const models=await b.listModels();this.model=models[0]?.id||'';this.send({type:'models',models});this.send({type:'state',state:'connected'});}catch(e){this.send({type:'error',message:e instanceof Error?e.message:'Unable to connect.'});this.send({type:'state',state:'error'});}}
private async generate(){const b=this.current();this.abort=new AbortController();this.send({type:'streamStart',backend:b.displayName,model:this.model});let answer='';for await(const event of b.streamChat(this.model,this.history,{},this.abort.signal)){if(event.type==='textDelta'){answer+=event.text;this.send(event);}else if(event.type==='error'){this.send({type:'error',message:event.error.message});}else if(event.type==='done'){this.send({type:'streamEnd'});}}if(answer)this.history.push(textMessage('assistant',answer));this.abort=undefined;}}
function getHtml(webview:vscode.Webview,uri:vscode.Uri){const script=webview.asWebviewUri(vscode.Uri.joinPath(uri,'dist','webview.js'));const style=webview.asWebviewUri(vscode.Uri.joinPath(uri,'dist','webview.css'));const nonce=Date.now().toString(36);return '<!doctype html><html><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src '+webview.cspSource+'; script-src \'nonce-'+nonce+'\';"><link rel="stylesheet" href="'+style+'"></head><body><div id="app"></div><script nonce="'+nonce+'" src="'+script+'"></script></body></html>';}
