import * as vscode from 'vscode'; import {parseClientMessage,type HostMessage,type ChatOptions} from './shared/messages.js'; import {Logger} from './shared/logger.js'; import {type BackendProfile} from './model/profiles.js'; import {createBackends} from './model/registry.js'; import {textMessage,type LgsMessage} from './model/types.js'; import type {ModelBackend} from './model/backend.js'; import {getFreshness,writeRepositoryIndex, type RepositoryIndex} from './intelligence/indexer.js'; import * as nodeFs from 'node:fs'; import * as nodePath from 'node:path'; import {SettingsManager} from './settings/configuration.js'; import {SettingsPanel as SettingsExperience} from './settings/panel.js'; import {loadProfiles} from './model/profiles.js';
type SavedChat={id:string;title:string;updatedAt:number;messages:LgsMessage[]};
export function activate(context:vscode.ExtensionContext):void{const logger=new Logger('LGS');const settings=new SettingsManager(context,vscode.workspace.workspaceFolders?.[0]?.uri.fsPath);const provider=new LgsViewProvider(context,logger,settings);context.subscriptions.push(vscode.window.registerWebviewViewProvider('lgs.sidebar',provider),vscode.commands.registerCommand('lgs.open',()=>vscode.commands.executeCommand('workbench.view.extension.lgs')),vscode.commands.registerCommand('lgs.settings',()=>new SettingsExperience(context,settings,()=>provider.refreshConnections(),()=>provider.refreshAppearance()).show()),vscode.commands.registerCommand('lgs.rebuildIndex',()=>rebuildIndex(logger)),vscode.commands.registerCommand('lgs.openCodebaseMap',()=>openCodebaseMap()));logger.info('Extension activated');void rebuildIndex(logger);}export function deactivate():void{}
class LgsViewProvider implements vscode.WebviewViewProvider{private view?:vscode.WebviewView;private profiles:BackendProfile[]=[];private backends=new Map<string,ModelBackend>();private profileId='';private model='';private history:LgsMessage[]=[];private abort?:AbortController;private options:ChatOptions={thinking:'off',approval:'on-request'};private chats:SavedChat[]=[];private chatId='';
constructor(private context:vscode.ExtensionContext,private logger:Logger,private settings:SettingsManager){this.profiles=loadProfiles(context);this.chats=context.globalState.get<SavedChat[]>('lgs.chats')||[];this.profileId=this.profiles[0]?.id||'';}private async rebuild(){const secrets=new Map<string,string>();const secretHeaders=new Map<string,Record<string,string>>();for(const p of this.profiles){if(p.secretName){const secret=await this.context.secrets.get(p.secretName);if(secret)secrets.set(p.secretName,secret);}const headers:Record<string,string>={};for(const name of p.secretHeaderNames){const value=await this.context.secrets.get('lgs.connection.'+p.id+'.header.'+name);if(value)headers[name]=value;}secretHeaders.set(p.id,headers);}this.backends=createBackends(this.profiles,p=>p.secretName?secrets.get(p.secretName):undefined,p=>secretHeaders.get(p.id)||{});}
async resolveWebviewView(view:vscode.WebviewView){this.view=view;await this.rebuild();view.webview.options={enableScripts:true,localResourceRoots:[this.context.extensionUri]};view.webview.html=getHtml(view.webview,this.context.extensionUri);view.webview.onDidReceiveMessage((raw:unknown)=>void this.receive(raw),undefined,this.context.subscriptions);this.send({type:'profiles',profiles:this.profiles.map(p=>({id:p.id,name:p.name,kind:p.kind})),selected:this.profileId});this.send({type:'options',options:this.options});this.refreshAppearance();this.sendChats();await this.listModels();}
private send(m:HostMessage){void this.view?.webview.postMessage(m);}private backend(){return this.backends.get(this.profileId)!;}private sendChats(){this.send({type:'chatList',chats:this.chats.map(c=>({id:c.id,title:c.title,updatedAt:c.updatedAt}))});}
private async receive(raw:unknown){const m=parseClientMessage(raw);if(!m){this.send({type:'error',message:'Invalid message.'});return;}if(m.type==='cancel'){this.abort?.abort();return;}if(m.type==='openSettings'){await vscode.commands.executeCommand('lgs.settings');return;}if(m.type==='newChat'){this.history=[];this.chatId='';this.send({type:'chatLoaded',messages:[]});return;}if(m.type==='loadChat'){const c=this.chats.find(x=>x.id===m.chatId);if(c){this.chatId=c.id;this.history=c.messages;this.send({type:'chatLoaded',messages:c.messages.filter(x=>x.role!=='system').map(x=>({role:x.role as 'user'|'assistant',text:x.content.map(y=>y.type==='text'?y.text:'[image]').join('')}))});}return;}if(m.type==='selectProfile'){if(this.backends.has(m.profileId)){this.profileId=m.profileId;this.model='';this.send({type:'profiles',profiles:this.profiles.map(p=>({id:p.id,name:p.name,kind:p.kind})),selected:this.profileId});await this.listModels();}return;}if(m.type==='selectModel'){this.model=m.model;return;}if(m.type==='setOptions'){this.options=m.options;this.send({type:'options',options:this.options});return;}if(m.type==='listModels'){await this.listModels();return;}if(m.type==='userMessage'){if(!this.model){await this.listModels();if(!this.model){this.send({type:'error',message:'No model was discovered for this profile. Check settings and connection.'});return;}}this.history.push(textMessage('user',m.text));await this.generate();}}
private async listModels(){const b=this.backend();if(!b)return;this.send({type:'state',state:'connecting'});try{const models=await b.listModels();this.model=models[0]?.id||'';this.send({type:'models',models,selected:this.model});this.send({type:'state',state:'connected'});}catch(e){this.send({type:'error',message:e instanceof Error?e.message:'Unable to connect or discover models.'});this.send({type:'state',state:'error'});}}
private async generate(){const b=this.backend();this.abort=new AbortController();this.send({type:'streamStart',backend:b.displayName,model:this.model});let answer='';for await(const event of b.streamChat(this.model,this.history,{temperature:this.options.thinking==='high'?0.8:this.options.thinking==='low'?0.2:0.5,maxTokens:1024},this.abort.signal)){if(event.type==='textDelta'){answer+=event.text;this.send(event);}else if(event.type==='error')this.send({type:'error',message:event.error.message});else if(event.type==='done')this.send({type:'streamEnd'});}if(answer)this.history.push(textMessage('assistant',answer));this.saveChat();this.abort=undefined;}
private saveChat(){if(!this.history.length)return;const c:SavedChat={id:this.chatId||Date.now().toString(36),title:this.history.find(x=>x.role==='user')?.content.map(x=>x.type==='text'?x.text:'').join('').slice(0,60)||'New chat',updatedAt:Date.now(),messages:this.history};this.chatId=c.id;this.chats=[c,...this.chats.filter(x=>x.id!==c.id)].slice(0,100);void this.context.globalState.update('lgs.chats',this.chats);this.sendChats();}
refreshAppearance(){const theme=this.settings.effective().find(x=>x.id==='appearance.theme')?.value;this.send({type:'appearance',theme:theme==='lgs-light'||theme==='lgs-dark'?theme:'vscode'});}
async refreshConnections(){this.profiles=loadProfiles(this.context);await this.rebuild();this.profileId=this.profiles.some(p=>p.id===this.profileId)?this.profileId:this.profiles[0]?.id||'';}
async updateProfiles(profiles:BackendProfile[],secret?:{name:string;value:string}){this.profiles=profiles;await this.context.globalState.update('lgs.profiles',profiles);if(secret)await this.context.secrets.store(secret.name,secret.value);await this.rebuild();this.profileId=this.profiles.some(p=>p.id===this.profileId)?this.profileId:this.profiles[0]?.id||'';if(this.view)this.send({type:'profiles',profiles:this.profiles.map(p=>({id:p.id,name:p.name,kind:p.kind})),selected:this.profileId});}}
function getHtml(webview:vscode.Webview,uri:vscode.Uri){const script=webview.asWebviewUri(vscode.Uri.joinPath(uri,'dist','webview.js'));const style=webview.asWebviewUri(vscode.Uri.joinPath(uri,'dist','webview.css'));const nonce=Date.now().toString(36);return '<!doctype html><html><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src '+webview.cspSource+'; script-src \'nonce-'+nonce+'\';"><link rel="stylesheet" href="'+style+'"></head><body><div id="app"></div><script nonce="'+nonce+'" src="'+script+'"></script></body></html>';}

async function rebuildIndex(logger:Logger):Promise<void>{const folder=vscode.workspace.workspaceFolders?.[0];if(!folder){void vscode.window.showWarningMessage('LGS: Open a workspace to index its repository.');return;}const root=folder.uri.fsPath;const file=nodePath.join(root,'.lgs','index.json');let previous:RepositoryIndex|undefined;try{previous=JSON.parse(nodeFs.readFileSync(file,'utf8')) as RepositoryIndex;}catch{ // A missing index is expected on first run.
}try{const index=writeRepositoryIndex(root,previous);logger.info('Repository index updated: '+index.files.length+' files');void vscode.window.showInformationMessage('LGS: Repository index updated.');}catch(error){logger.error(error instanceof Error?error.message:'Repository index failed.');void vscode.window.showErrorMessage('LGS: Could not rebuild repository index.');}}
async function openCodebaseMap():Promise<void>{const folder=vscode.workspace.workspaceFolders?.[0];if(!folder){void vscode.window.showWarningMessage('LGS: Open a workspace to view the Codebase Map.');return;}const root=folder.uri.fsPath;try{const index=JSON.parse(nodeFs.readFileSync(nodePath.join(root,'.lgs','index.json'),'utf8')) as RepositoryIndex;const freshness=getFreshness(root,index);if(freshness.index==='stale')void vscode.window.showWarningMessage('LGS: Codebase Map is stale. Run LGS: Rebuild Repository Index.');}catch{void vscode.window.showWarningMessage('LGS: No repository index found. Run LGS: Rebuild Repository Index.');}const document=await vscode.workspace.openTextDocument(vscode.Uri.joinPath(folder.uri,'.lgs','CODEBASE_MAP.md'));await vscode.window.showTextDocument(document);}
