import { ToolFailure, type ToolPermission } from '../tools/types.js';
import { ToolRegistry, toolError } from '../tools/framework.js';
import type { MemoryKind } from './types.js';
import type { ProjectMemoryStore } from './memory.js';
import type { WorkspaceSkillStore } from './skills.js';

const READ: ToolPermission = { access: 'read-only', scope: 'workspace', network: false, category: 'read-only' };
const WRITE: ToolPermission = { access: 'execute', scope: 'workspace', network: false, category: 'process' };
const KINDS = ['architecture-decision', 'project-convention', 'debugging-discovery', 'implementation-pattern', 'approved-behavior'];

export function registerKnowledgeTools(registry: ToolRegistry, skills: WorkspaceSkillStore, memories: ProjectMemoryStore): ToolRegistry {
  registry.register({ id: 'list_workspace_skills', description: 'List workspace skills with activation metadata and estimated token cost; skill content is not injected automatically.', permission: READ, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: () => { const items = skills.list().map(skill => ({ name: skill.name, description: skill.description, applicableTasks: skill.applicableTasks, activationRules: skill.activationRules, estimatedTokenCost: skill.estimatedTokenCost, path: skill.path, supportingFiles: skill.supportingFiles })); return { data: { skills: items }, resultCount: items.length, source: 'filesystem' }; } });
  registry.register({ id: 'activate_skill', description: 'Manually activate one named workspace skill and return its instructions plus supporting-file paths.', permission: READ, argumentSchema: { type: 'object', properties: { name: { type: 'string', minLength: 1, maxLength: 100 } }, required: ['name'], additionalProperties: false }, execute: args => { const skill = skills.get(args.name as string); if (!skill) throw new ToolFailure(toolError('not_found', 'Workspace skill was not found.')); return { data: skill, resultCount: 1, source: 'filesystem' }; } });
  registry.register({ id: 'select_relevant_skills', description: 'Select only relevant workspace skills for the current task within an explicit token budget. The Manager may activate returned skills selectively.', permission: READ, argumentSchema: { type: 'object', properties: { task: { type: 'string', minLength: 1, maxLength: 4000 }, maxTokens: { type: 'integer', minimum: 1, maximum: 20_000 } }, required: ['task'], additionalProperties: false }, execute: args => { const selected = skills.select(args.task as string, args.maxTokens as number ?? 1_500); return { data: { skills: selected, estimatedTokenCost: selected.reduce((sum, skill) => sum + skill.estimatedTokenCost, 0) }, resultCount: selected.length, source: 'filesystem' }; } });
  registry.register({ id: 'remember_project_knowledge', description: 'Persist concise durable project knowledge. Do not store task transcripts or ephemeral task state.', permission: WRITE, argumentSchema: { type: 'object', properties: { kind: { type: 'string', enum: KINDS }, content: { type: 'string', minLength: 1, maxLength: 8000 }, tags: { type: 'array', items: { type: 'string', minLength: 1, maxLength: 80 }, maxItems: 20 } }, required: ['kind', 'content'], additionalProperties: false }, execute: args => ({ data: memories.remember({ kind: args.kind as MemoryKind, content: args.content as string, tags: args.tags as string[] | undefined }), resultCount: 1, source: 'filesystem' }) });
  registry.register({ id: 'search_project_memory', description: 'Retrieve only high-relevance durable project memories within a token budget. This does not include task state or old conversations.', permission: READ, argumentSchema: { type: 'object', properties: { query: { type: 'string', minLength: 1, maxLength: 4000 }, maxTokens: { type: 'integer', minimum: 1, maximum: 20_000 } }, required: ['query'], additionalProperties: false }, execute: args => { const found = memories.search(args.query as string, args.maxTokens as number | undefined); return { data: { memories: found, estimatedTokenCost: found.reduce((sum, memory) => sum + Math.ceil(memory.content.length / 4), 0) }, resultCount: found.length, source: 'filesystem' }; } });
  registry.register({ id: 'get_memory_state', description: 'Inspect local long-term-memory enablement, size, retention, and entry count.', permission: READ, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: () => ({ data: memories.inspect(), resultCount: 1, source: 'filesystem' }) });
  registry.register({ id: 'set_project_memory_enabled', description: 'Enable or disable long-term-memory retrieval and saving for this LGS session.', permission: WRITE, argumentSchema: { type: 'object', properties: { enabled: { type: 'boolean' } }, required: ['enabled'], additionalProperties: false }, execute: args => { memories.setEnabled(args.enabled as boolean); return { data: memories.inspect(), resultCount: 1, source: 'filesystem' as const }; } });
  registry.register({ id: 'configure_project_memory_retention', description: 'Set local long-term-memory retention and maximum entry limits for this LGS session.', permission: WRITE, argumentSchema: { type: 'object', properties: { retentionDays: { type: 'integer', minimum: 1, maximum: 3650 }, maxEntries: { type: 'integer', minimum: 1, maximum: 10000 } }, required: ['retentionDays', 'maxEntries'], additionalProperties: false }, execute: args => { memories.configureRetention(args.retentionDays as number, args.maxEntries as number); return { data: memories.inspect(), resultCount: 1, source: 'filesystem' as const }; } });
  registry.register({ id: 'delete_project_memory', description: 'Permanently delete one durable memory by ID.', permission: WRITE, argumentSchema: { type: 'object', properties: { id: { type: 'string', minLength: 1, maxLength: 100 } }, required: ['id'], additionalProperties: false }, execute: args => ({ data: { deleted: memories.delete(args.id as string) }, resultCount: 1, source: 'filesystem' }) });
  registry.register({ id: 'compact_project_memory', description: 'Apply configured local retention and size limits to durable memory.', permission: WRITE, argumentSchema: { type: 'object', properties: {}, additionalProperties: false }, execute: () => ({ data: memories.compact(), resultCount: 1, source: 'filesystem' }) });
  return registry;
}
